name: fair-software

on:
  workflow_dispatch:
  schedule:
    # every 14 days at 12:00, see https://crontab.guru
    - cron: '0 12 */14 * *'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: fair-software/howfairis-github-action@0.2.1
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
